## Week 11 Assignment - W200 Python Fundamentals for Data Science, UC Berkeley MIDS

Write code in this Jupyter Notebook to solve the following problems. Please upload this **Notebook** with your solutions to your GitHub repository in your SUBMISSIONS/week_11 folder by 11:59PM PST the night before class.

This homework assignment is Week 11 which corresponds to the Unit #10 async. If you turn-in anything on ISVC please do so under the Week 11 Assignment category. (Apologies for the confusion)

## Objectives

- Demonstrate use of map and filter commands
- Practice list comprehensions and lambda functions
- Understand different ways to manipulate and perform calculations on Numpy arrays including:
- Changing datatypes, getting the max values in each column and row, calculating the mean of a matrix
- Matrix value comparisons and slicing of values

## 1. List, Mapping, Filtering, and Reducing Comprehensions

**A.** Write a function that doubles any number (integer or floating type values), reverses the content if it is a string, and does nothing if it is another kind of value.

Use that function in a **list comprehension** and apply it to the below list of data.

Example of the first two entries:
```
['cinesra', 10, ...]
```

In [68]:
fix_me = ['arsenic', 5, 'ball', 2, 47, 123, 
          'comprehensions', 'list', 5.5, 
          8343.23, 'shishkabob', True]

In [69]:
# Put the function here
def fix(a):
    if type(a) is int or type(a) is float:
        return a*2
    elif type(a) is str:
        return a[::-1]
    else:
        return a

In [70]:
# Put the list comprehension (which calls your function above) here 
print([fix(x) for x in fix_me])

['cinesra', 10, 'llab', 4, 94, 246, 'snoisneherpmoc', 'tsil', 11.0, 16686.46, 'bobakhsihs', True]


**B.** Now apply your function made in **A** above using a **map**.

In [71]:
print(list(map(fix, fix_me)))

['cinesra', 10, 'llab', 4, 94, 246, 'snoisneherpmoc', 'tsil', 11.0, 16686.46, 'bobakhsihs', True]


**C.** Repeat step **B**, except use **filter** to remove any number values that are less than 5 after your map.  You may use a separate function to filter (or could do it with one statement).

In [72]:
def fix_filter(a):
    if type(a) is int or type(a) is float:
        if a < 5:
            return False
        else:
            return True
    else:
        return True      

In [73]:
b_list = list(map(fix, fix_me))
c_list = list(filter(fix_filter, b_list))
print(c_list)

['cinesra', 10, 'llab', 94, 246, 'snoisneherpmoc', 'tsil', 11.0, 16686.46, 'bobakhsihs', True]


**D.** Update your solution to **C** to use **lambda** expressions instead of functions for both the map and the filter. This needs to be done in one statement. If you are having trouble converting your functions to lambda functions, try to understand how the sample code below is working:
```python
y = lambda symbol: 'X' if symbol==True else 'O' if symbol==False else ' '
```
Hint: It might be helpful to test the map part and the filter part as separate statements and then combine them into one statement for the final answer.

In [74]:
print(list(map(lambda x: fix(x), fix_me)))

['cinesra', 10, 'llab', 4, 94, 246, 'snoisneherpmoc', 'tsil', 11.0, 16686.46, 'bobakhsihs', True]


# 2. Generating Random Data and Filtering That Data

In this next section, we will work with NumPy. Please run your the cell below to set your random seed. (This makes the 'randomness' of the array the same for everyone)

In [75]:
# Do NOT change this code!
import numpy as np
np.random.seed(25)
ar = np.random.randn(1000)

Now we will start playing around with this data. This part of the assignment will prompt you to follow a series of steps and output your answers. 

For the first number of these steps, the problem asks you to modify the dataset and use the new dataset in the next step.  For these steps, you will use the `ar` value that we created above, and after each step, you should set `ar` to be the new `ar` value. Using this process, you will update your dataset each step of the way. The later steps do not ask for this. It sounds confusing but there is a note on what to do on each question.  

Please run the cell below as the first step:

**Multiply all values by 100 and assign this back to ar**

So your answer will be the following:

In [76]:
# Do NOT change this code!
ar = ar * 100
ar

array([  2.28273090e+01,   1.02689030e+02,  -8.39584849e+01,
        -5.91181518e+01,  -9.56888297e+01,  -2.22325694e+01,
        -6.19915108e+01,   1.83790458e+02,  -2.05323076e+02,
         8.68583052e+01,  -9.20734440e+01,  -2.32311864e+01,
         2.15295690e+02,  -1.33466147e+02,   7.63796505e+00,
        -1.24608928e+02,   1.20227231e+02,  -1.04994158e+02,
         1.05661011e+02,  -4.19677671e+01,   2.29484234e+02,
        -2.59448738e+02,   2.82275640e+02,   6.80888923e+01,
        -1.57769345e+02,  -1.97625359e+02,   5.33339823e+01,
        -2.90869712e+01,  -5.13519669e+01,   1.98262608e+02,
         2.26001050e+01,  -1.83990496e+02,   1.60767083e+02,
         3.88291936e+01,   3.99732064e+01,   4.05476600e+01,
         2.17001772e+01,  -6.33439103e+01,   2.46621529e+01,
        -1.93954552e+02,   1.14059633e+01,  -1.88534140e+02,
         2.43080482e+01,  -7.05480672e+01,   3.64627615e+01,
        -5.02952163e+01,  -2.25751546e+01,  -5.65537733e+01,
         1.03395013e+01,

*the first 3 values should be*
```
2.28273090e+01,   1.02689030e+02,  -8.39584849e+01,
```

**A.** Now convert the `ar` matrix into a matrix of 8-bit integers and assign this back to `ar`.

In [77]:
ar =ar.astype(int) 


The first 3 values should be:
```
 22,  102,  -83,
```
And the length should be 1000.

**B.** Reshape the array into a set of five columns with 200 rows. Replace the original `ar` array with this new matrix.

In [78]:
ar = ar.reshape(200,5)
print(ar)

[[  22  102  -83  -59  -95]
 [ -22  -61  183 -205   86]
 [ -92  -23  215 -133    7]
 [-124  120 -104  105  -41]
 [ 229 -259  282   68 -157]
 [-197   53  -29  -51  198]
 [  22 -183  160   38   39]
 [  40   21  -63   24 -193]
 [  11 -188   24  -70   36]
 [ -50  -22  -56   10  201]
 [ 109  166  -62  162  117]
 [ -37  -54   28  -20  118]
 [  72  -22 -162   31 -116]
 [  31   47   57   50  -62]
 [ -34 -206   76  112   16]
 [ -96   49  -55   -8  196]
 [  -6  -85   42  -27 -137]
 [  -9   83  -78  104  -64]
 [-189   -9 -135   49 -114]
 [ -53  -91  -21   19  -32]
 [-172   76   44 -213  102]
 [ -58    4   56  142    0]
 [ -29   23   67 -134  -60]
 [ -16  -65  -19   17    3]
 [ 130  -53   52   38  180]
 [ 251  -24   20  -30   15]
 [   3  -32  -77  -33 -202]
 [ 141  -74 -155   96  -18]
 [ 202 -109   43  -73   16]
 [ -67  -16  -54  -35  168]
 [   9  112  -45   87 -114]
 [ -85   93  -17 -215  -28]
 [ -90   48   -4   64    1]
 [ -97 -197 -126 -100 -304]
 [  39 -194   53   37  204]
 [  30  -66  -19   9

**C.** Now that `ar` is a matrix, get the maximum and minimum values from the matrix both row-wise and column-wise. Be sure to remember how many total values you should be outputting - in the first cell should be one value for every row; in the second cell should be one value for each column. Do **NOT** assign this to `ar`, just show the values.

In [24]:
print(np.amax(ar,axis=1))
print(np.amin(ar,axis=1))

[102 183 215 120 282 198 160  40  36 201 166 118  72  57 112 196  42 104
  49  19 102 142  67  17 180 251   3 141 202 168 112  93  64 -97 204 172
 169 192 138 120 135 186  64  40 141 106 157  80  45 138 168  24 154  68
 201 173 199 139 206  28 132  93 140  58 111  83 126 137 249 111 146  70
 377 124  89 186  43  98 106  58 153 191 158 146  64 156 205  86 153 148
 125 135 170  72 283  40 -30  80 123  41 117  69  71  62  38  91  33 106
  64 114 121  44  98 116 212  18 245  67 124 117 126  37  93 173 100  97
 144 143 146  74 118  82 133 231  57 170  50  91 112  24 139 119 289 169
 126 186 110 170  68 145 115 199  54 163 102 232 138 136  79  98 141 217
  68 166  88  86  52  93  75  81 126 195 134  -9 123 258 142 377  79 147
 192  81  48 100 198 136 -51 166 156 292 142 129 130  11 265 114  93 185
 200 127]
[ -95 -205 -133 -124 -259 -197 -183 -193 -188  -56  -62  -54 -162  -62 -206
  -96 -137  -78 -189  -91 -213  -58 -134  -65  -53  -30 -202 -155 -109  -67
 -114 -215  -90 -304 -194  -66 -193

In [25]:
print(np.amax(ar,axis=0))
print(np.amin(ar,axis=0))


[251 283 377 258 377]
[-270 -280 -307 -284 -304]


**D.** Now that we have gotten the minimum and maximum values for the rows and columns, get the mean of the entire matrix. This should be one specific value. Do **NOT** assign this to `ar`, just show the value.

In [27]:
armean = np.mean(ar)
print(armean)

3.561


**E.** What is the total number of values in the `ar` matrix that are less than the mean calculated in **D** above? Do **NOT** assign this to `ar`, just show the value.

In [57]:
np.sum(ar<armean)

501

**F.** What are the total number of values in *each row* that are greater than the mean calculated in **D** above? (Remember, if we are doing a row-oriented comparison, how many numbers should be in our output array?) Do **NOT** assign this to `ar`, just show the values.

In [59]:
def compare(a):
    return np.sum(a>armean)
np.apply_along_axis(compare, 1, ar)

array([2, 2, 2, 2, 3, 2, 4, 3, 3, 2, 4, 2, 2, 4, 3, 2, 1, 2, 1, 1, 3, 3, 2,
       1, 4, 3, 0, 2, 3, 1, 3, 1, 2, 0, 4, 3, 2, 1, 3, 3, 3, 3, 2, 1, 2, 1,
       4, 1, 1, 3, 4, 2, 5, 2, 2, 1, 5, 5, 2, 1, 1, 3, 3, 3, 2, 3, 2, 2, 3,
       4, 2, 2, 3, 2, 3, 2, 2, 4, 3, 2, 2, 3, 4, 5, 1, 3, 3, 3, 2, 4, 4, 1,
       2, 4, 2, 3, 0, 2, 2, 1, 2, 4, 4, 2, 1, 5, 2, 3, 3, 2, 3, 2, 2, 4, 2,
       1, 2, 1, 2, 3, 3, 1, 2, 3, 4, 2, 3, 3, 2, 3, 3, 1, 5, 3, 1, 3, 4, 1,
       2, 1, 1, 2, 2, 3, 2, 3, 3, 3, 2, 2, 2, 3, 2, 3, 3, 3, 2, 3, 4, 1, 2,
       5, 1, 3, 3, 3, 3, 3, 3, 2, 2, 4, 4, 0, 3, 3, 2, 3, 3, 4, 1, 4, 2, 3,
       3, 5, 0, 2, 3, 2, 4, 1, 2, 1, 3, 2, 3, 4, 1, 5])

**G.** How many zeros are in the matrix that we have? Do **NOT** assign this to `ar`, just show the value.

In [61]:
np.sum(ar==0)

8

**H.** Lastly, sum all the values that are: 
- (Greater than 100) and (less than 5 and greater than or equal to -20). 

Do **NOT** assign this to `ar`, just show the value.

In [67]:
np.sum(ar > 100) + np.sum((ar < 5) & (ar >= -20))

276